---
:FEEDS:
  - 'http://ci-release2.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://clbuild002.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft01.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft02.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft03.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft04.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft05.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft06.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft07.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft08.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft09.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft10.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft11.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft12.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft13.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft14.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft15.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft16.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft18.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft19.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft20.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft21.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://ft22.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://sf0307.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://sfci-l01.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://sfci-l02.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://sfci-l03.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://sfci-l05.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://sfci-l06.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://sfci-l07.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://sfci-l08.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://sfci-l09.gid.gap.com:8080/dashboard/cctray.xml'
  - 'http://sfci-reg10.gid.gap.com:8080/dashboard/cctray.xml'
